### ISSUE TITLE
AsyncRead, AsyncWrite traits

### ISSUE THREAD

**Issue by tmandry** [rust-lang/wg-async#23]
We need an async form of the Read and Write traits.

There are multiple versions of this in the ecosystem:

futures: [AsyncRead](https://docs.rs/futures/latest/futures/io/trait.AsyncRead.html), [AsyncWrite](https://docs.rs/futures/latest/futures/io/trait.AsyncWrite.html)
tokio: [AsyncRead](https://docs.rs/tokio/latest/tokio/io/trait.AsyncRead.html), [AsyncWrite](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html)
async_std: [Read](https://docs.rs/async-std/latest/async_std/io/trait.Read.html), [Write](https://docs.rs/async-std/latest/async_std/io/trait.Write.html)

Relevant design decisions:

- How to handle `ReadBuf` (https://github.com/rust-lang/rust/issues/78485), should we include a method without it like `Read` has
- Whether to include vectored I/O

**Comment by ids1024** [comment]
> async_std

These re-export the versions in `futures`.

These traits are a fair bit harder to implement than the normal std versions of `Read`/`Write`, since it's necessary to implement `fn poll_read()` rather than something like `async fn read()`. It seems unsatisfactory to me to stabilize something like that without making it easier to implement.

**Comment by Darksonn** [comment]
@ids1024 In principle that same complaint could be targeted at the `Stream` trait, which is quite a bit further towards stabilization.

**Comment by djc** [comment]
> * How to handle ReadBuf (rust-lang/rust#78485), should we include a method without it like `Read` has

Seems to me that `Read` wouldn't have the non-buf version if we'd had the `ReadBuf` abstraction at the time it was stabilized. In other words, I definitely think it would be preferable to require the buf kind for new traits.

> These traits are a fair bit harder to implement than the normal std versions of `Read`/`Write`, since it's necessary to implement `fn poll_read()` rather than something like `async fn read()`. It seems unsatisfactory to me to stabilize something like that without making it easier to implement.

While we still don't have GAT, pretty sure we wouldn't want to require boxing at this level of the stack.

Also, implementing these traits will be relatively rare IMO.

**Comment by taiki-e** [comment]
it shouldn't probably be difficult to integrate both io traits once https://github.com/rust-lang/rust/issues/69941 and https://github.com/rust-lang/rust/issues/78485 are stable. 

AFAIK, they should be sufficient to meet the requirements that tokio requires for async io trait. And, futures tend not to actively add features that are not stable in the standard library.
(Aside from the question of whether to default to poll_read or poll_read_buf.)

related: https://github.com/rust-lang/futures-rs/issues/2209, https://github.com/rust-lang/futures-rs/pull/1826, https://github.com/rust-lang/futures-rs/issues/1761

**Comment by lqf96** [comment]
We may also want to standardize the `AsyncSeek` trait since it's present in [`futures`](https://docs.rs/futures/0.3.13/futures/io/trait.AsyncSeek.html), [`tokio`](https://docs.rs/tokio/1.4.0/tokio/io/trait.AsyncSeek.html) and [`async_std`](https://docs.rs/async-std/1.9.0/async_std/io/trait.Seek.html)...

**Comment by tmandry** [comment]
There is progress being made on moving the Error trait into core: https://github.com/rust-lang/project-error-handling/issues/3

**Comment by tmandry** [comment]
Closing in favor of https://github.com/nrc/portable-interoperable/issues/5.
