### ISSUE TITLE
RFC: async trait

### ISSUE THREAD

**Issue by tmandry** [rust-lang/wg-async#289]
**This is a roadmap item for wg-async. You can view the roadmap here: https://github.com/orgs/rust-lang/projects/28**

Something like `async Trait` notation with a hook for Send bounds: `async(Send) Trait`

**Comment by Noah-Kennedy** [comment]
Could you add a description here?

**Comment by tmandry** [comment]
Draft RFC is in https://hackmd.io/Y--peo4xR2maBQXG_XHbGQ.

**Comment by tmandry** [comment]
Status update: @eholk Would update this RFC to only include `async(Send)` and split out the rest.

**Comment by tmandry** [comment]
We decided not to pursue this for now, as trait transformers #309 is strictly more powerful.
