### ISSUE TITLE
Open discussion: 2024-01-11

### ISSUE THREAD

**Issue by traviscross** [rust-lang/wg-async#328]
# Summary

We're planning an open discussion of WG-async topics on 2024-01-11.

# About this issue

This issue is a proposal for a WG-async [meeting][].

[meeting]: https://rust-lang.github.io/wg-async/meetings.html

**Comment by yoshuawuyts** [comment]
I might have a conflict for the triage on 2023-01-08 - can we perhaps move discussion of https://github.com/rust-lang/rust/pull/119550#discussion_r1440723495 to this slot? That would give us a bit more time too.

cc/ @compiler-errors - would that work for you?

**Comment by compiler-errors** [comment]
I should be able to make it.
